from pydantic import BaseModel
from enum import Enum

class MigrationState(Enum):
    REQUESTED = "REQUESTED"
    PATIENT_AUTHORIZED = "PATIENT_AUTHORIZED"
    POLICY_LEGAL_CHECK = "POLICY_LEGAL_CHECK"
    TRANSFER_AUTH_ISSUED = "TRANSFER_AUTH_ISSUED"
    FHIR_EXPORT = "FHIR_EXPORT"
    VALIDATION = "VALIDATION"
    HASH_GENERATION = "HASH_GENERATION"
    ENCRYPTED_TRANSFER = "ENCRYPTED_TRANSFER"
    DESTINATION_VALIDATION = "DESTINATION_VALIDATION"
    HASH_VERIFICATION = "HASH_VERIFICATION"
    IMPORT_COMPLETED = "IMPORT_COMPLETED"
    SOURCE_ARCHIVED_READONLY = "SOURCE_ARCHIVED_READONLY"
    COMPLETED = "COMPLETED"

class TransferStatus(BaseModel):
    # TODO: Implement in Segment 12
    pass

class TransferRequestCreate(BaseModel):
    # TODO: Implement in Segment 12
    pass
