"use client";
import { useEffect, useState } from "react";
import { api, type Repository } from "@/lib/api";
import { Card, Field, PortalShell } from "@/components/portal-shell";
export default function AdminPortal() {
  const [repos,setRepos]=useState<Repository[]>([]); const [healthId,setHealthId]=useState(""); const [source,setSource]=useState(""); const [destination,setDestination]=useState(""); const [result,setResult]=useState<unknown>(null); const [error,setError]=useState("");
  useEffect(()=>{api.repositories().then(setRepos).catch(e=>setError(e instanceof Error?e.message:"Could not load repositories"))},[]);
  async function migrate(){setError("");try{setResult(await api.createTransfer({health_id:healthId,source_repository_id:source,destination_repository_id:destination,purpose:"MIGRATION",scope:"FHIR"}))}catch(e){setError(e instanceof Error?e.message:"Migration request failed")}}
  return <PortalShell title="Admin Portal" description="Repository registry and controlled EHR migration coordination."><div className="grid gap-5 lg:grid-cols-2"><Card title="Jurisdictional repositories"><div className="space-y-3">{repos.map(r=><div key={r.id} className="rounded-lg border p-3"><div className="flex justify-between"><strong>{r.name}</strong><span className="text-xs">{r.status}</span></div><p className="text-xs text-slate-500">{r.code} · {r.jurisdiction} · {r.base_url}</p></div>)}{error&&<p className="text-sm text-red-600">{error}</p>}</div></Card><Card title="Start EHR migration"><div className="space-y-3"><Field value={healthId} onChange={e=>setHealthId(e.target.value)} placeholder="Patient Health ID"/><select value={source} onChange={e=>setSource(e.target.value)} className="w-full rounded-lg border px-3 py-2 text-sm"><option value="">Source repository</option>{repos.map(r=><option key={r.id} value={r.id}>{r.code} — {r.name}</option>)}</select><select value={destination} onChange={e=>setDestination(e.target.value)} className="w-full rounded-lg border px-3 py-2 text-sm"><option value="">Destination repository</option>{repos.map(r=><option key={r.id} value={r.id}>{r.code} — {r.name}</option>)}</select><button onClick={migrate} className="rounded-lg bg-slate-900 px-4 py-2 text-sm text-white">Create migration request</button>{result&&<pre className="overflow-auto rounded-lg bg-slate-50 p-3 text-xs">{JSON.stringify(result,null,2)}</pre>}</div></Card></div></PortalShell>;
}