"use client";
import { useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { beginLogin, ROLE_CONFIG, type UserRole } from "@/lib/auth";
const validRoles: UserRole[] = ["patient", "provider", "admin", "auditor"];
export default function RoleLoginPage() {
  const params = useParams<{ role: string }>(); const role = params.role as UserRole; const config = validRoles.includes(role) ? ROLE_CONFIG[role] : null; const [starting, setStarting] = useState(false); const [error, setError] = useState("");
  if (!config) return <main className="flex min-h-screen items-center justify-center bg-slate-50 px-6"><div className="rounded-xl border bg-white p-8 text-center shadow-sm"><h1 className="text-xl font-bold">Portal not found</h1><Link href="/login" className="mt-4 inline-block text-sm underline">Choose another portal</Link></div></main>;
  async function login() { setStarting(true); setError(""); try { await beginLogin(role); } catch (reason: unknown) { setStarting(false); setError(reason instanceof Error ? reason.message : "Unable to start login."); } }
  return <main className="flex min-h-screen items-center justify-center bg-slate-50 px-6"><div className="w-full max-w-md rounded-2xl border bg-white p-8 shadow-sm"><Link href="/" className="text-sm font-semibold text-slate-500">← HealthNet</Link><p className="mt-8 text-sm font-semibold uppercase tracking-wider text-slate-500">Secure sign-in</p><h1 className="mt-2 text-3xl font-bold">{config.label} Portal</h1><p className="mt-3 text-sm leading-6 text-slate-600">{config.description}</p><div className="mt-6 rounded-lg bg-slate-50 p-4 text-sm text-slate-600">You will be securely redirected to HealthNet Keycloak to authenticate. Your role is checked before you enter this portal.</div>{error && <p className="mt-4 text-sm text-red-600">{error}</p>}<button onClick={login} disabled={starting} className="mt-6 w-full rounded-lg bg-slate-900 px-4 py-3 text-sm font-semibold text-white disabled:opacity-60">{starting ? "Redirecting…" : "Sign in as " + config.label}</button><Link href="/login" className="mt-5 block text-center text-sm text-slate-500 underline">Choose a different portal</Link></div></main>;
}